version: 2
updates:
- package-ecosystem: "docker"
  directory: "/"
  commit-message:
    prefix: "docker"
  labels: [ 'docker' ]
  assignees:
  - "Harvester57"
  schedule:
    interval: "weekly"
  groups:
    docker-dependencies:
      applies-to: version-updates
      patterns:
      - "*"
- package-ecosystem: "github-actions"
  directory: "/"
  commit-message:
    prefix: "actions"
  labels: [ 'github-actions' ]
  assignees:
  - "Harvester57"
  schedule:
    interval: "weekly"
  groups:
    actions-dependencies:
      applies-to: version-updates
      patterns:
      - "*"
